In [2]:
import torch
import numpy as np

In [ ]:
# 텐서 초기화
data = [[1, 2], [3, 4]]
xdata = torch.tensor(data)
print(xdata)
print(xdata.ndim)

tensor([[1, 2],
        [3, 4]])
2


In [6]:
# 다른 텐서로부터 생성
x_ones = torch.ones_like(xdata)    # 속성(모양, 자료형) 유지
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(xdata, dtype=torch.float) # 속성 오버라이드
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5929, 0.5583],
        [0.2950, 0.2162]]) 



In [ ]:
# 무작위 또는 상수 값을 사용
shape = (2, 3)
rand_tensor = torch.rand(shape)    # 랜덤한 값의 행렬
ones_tensor = torch.ones(shape)    # 1행렬(항등행렬)
zeros_tensor = torch.zeros(shape)    # 0행렬

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2461, 0.8898, 0.3856],
        [0.9666, 0.2656, 0.2240]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# 속성
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
# 텐서 연산
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

In [ ]:
# numpy식 표준 인덱싱, 슬라이싱
tensor = torch.ones(4, 4) 
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [15]:
# 텐서 곱(요소별 곱)
print(tensor.mul(tensor))    # tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
# 두 텐서 간 행렬 곱(matrix multiplication)
print(tensor.matmul(tensor.T))    # tensor # tensor.T 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
# 바꿔치기(in-place 연산, '_' 접미사를 갖음)
print(tensor, "\n")
tensor.add_(5)
print(tensor)

# 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 
#   따라서, 사용을 권장하지 않습니다.

#### tensor with NumPy

In [18]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [19]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [21]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
