In [2]:
import torch

In [3]:
x_auto_grad = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x_auto_grad * 2       # y = [2, 4, 6]
y += 3          # in-place 연산 (y = y + 3이 아님!)

In [4]:
x = torch.tensor([1.0, 2.0, 3.0])

Autograd에서 미분(differentiation)

In [29]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [30]:
Q = 3*a**3 - b**2    # Q=3a^3−b^2

In [ ]:
# case1. 직접 가중치 전달
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)    # 가중치 전달

print(a.grad, b.grad)

tensor([36., 81.]) tensor([-12.,  -8.])


In [ ]:
# case2. 스칼라로 만든 후 미분
loss = Q.sum() # Q1 + Q2 로 합쳐서 스칼라로 만듦
loss.backward()

print(loss)

tensor(53., grad_fn=<SumBackward0>)


In [ ]:
# 수집된 변화도가 올바른지 확인
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
